version: "3.1"

services:
  spotifywidget:
    image: spotifywidget:latest
    container_name: spotifywidget
    networks:
      - sandbixproxy_mynet

networks:
  sandbixproxy_mynet:
    external: true